# Generated by Django 5.2.1 on 2025-07-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
