# Generated by Django 5.2.1 on 2025-07-25 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
